services:
  - type: web
    name: musicplayer-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn musicPlayer.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
